name: Push to Dev branch

trigger:
  branches:
    include:
      - 'dev'
    exclude:
      - 'main'

pool:
  name: WSL Agent

steps:
- script: |
    terraform fmt
    terraform init
    terraform validate
  workingDirectory: /home/wsladmin/azure-repos/Terraform_Projects/dev
  displayName: 'Terraform Init and Validate'

- script: |
    terraform plan
  workingDirectory: /home/wsladmin/azure-repos/Terraform_Projects/dev
  displayName: 'Terraform Plan' 